var targetContainer = $(".target-output"),
templateDefined = $(".target-output").data("template-chosen"),
template = $("#mustacheTempalte_"+templateDefined).html();

var shows = { "shows" : [ 

{
"name" : "Quadruple Room with Private Bathroom",
"demand": true,
"choose_bed" : false,
"quantity" : "4",
"old_price" : "9318",
"price" : "7765",
"private_bathroom" : true,
"wifi": true,
	"female_only" : "false",
"private" : "private",
"refundable" : false,
"breakfast" : true,
},
{
"name" : "Room with 8 beds and Private Bathroom",
"demand": false,
"cancelation": true,
"choose_bed" : true,
"quantity" : "8",
"old_price" : "10962",
"price" : "9135",
"wifi": true,
	
"private_bathroom" : true,
	"female_only" : "true",
	"private" : "private",
"refundable" : false,
"breakfast" : false
},
{
"name" : "Bed in 8-Bed Mixed Dormitory Room",
"demand": false,
"cancelation": true,
"pay_arrive": true,
"choose_bed" : true,
"quantity" : "8",
"old_price" : "14980.8",
"wifi": false,
	"price" : "12484",

"private_bathroom" : true,
"female_only" : "false",
"private" : "Shared",
"refundable" : false,
"breakfast" : false
},
{
	"name" : "Bed in 10-Bed Mixed Dormitory Room",
	"demand": false,
	"cancelation": true,
"pay_arrive": true,
"choose_bed" : false,
"quantity" : "10",
	"old_price" : "17624.39",
	"wifi": true,
	"price" : "14687",
"private_bathroom" : false,
"female_only" : "false",
"private" : "private",
"refundable" : true,
"breakfast" : false
},
{
"name" : "Bed in 3-Bed Female Dormitory Room",
"demand": true,
"choose_bed" : false,
"quantity" : "3",
"old_price" : "1689.6",
"price" : "1408",
"private_bathroom" : false,
	"wifi": false,
	"female_only" : "true",
				"private" : "Shared",
"refundable" : true,
"breakfast" : true,
},
{
"name" : "Bed in 4-Bed Mixed Dormitory Room",
"demand": true,
"cancelation": true,
"choose_bed" : false,
"quantity" : "4",
"old_price" : "1988.39",
"price" : "1657",
"wifi": true,
	"private_bathroom" : false,
"female_only" : "false",
"private" : "Shared",
"refundable" : true,
"breakfast" : false
},
{
"name" : "Bed in 6-Bed Mixed Dormitory Room",
"demand": true,
"cancelation": true,
	"choose_bed" : true,
"quantity" : "6",
"old_price" : "1872",
"price" : "1560",
"wifi": true,
	
"private_bathroom" : false,
"female_only" : "false",
"private" : "Shared",
"refundable" : true,
"breakfast" : false
},
{
"name" : "Twin Room with Private Bathroom",
"demand": true,
"pay_arrive": true,
"choose_bed" : false,
"quantity" : "2",
"old_price" : "2203.2",
"price" : "1836",
"wifi": false,
	"private_bathroom" : true,
"female_only" : "false",
"private" : "private",
"refundable" : false,
"breakfast" : true,
},
{
"name" : "Room with 6 beds and Private Bathroom",
"demand": false,
	"choose_bed" : true,
"quantity" : "6",
"old_price" : "2178",
"price" : "1815",
"private_bathroom" : true,
"wifi": true,
	"female_only" : "false",
"private" : "private",
"refundable" : false,
"breakfast" : true,
}
] };


var html = Mustache.render(template, shows);

$(targetContainer).html(html);