var targetContainer = $(".target-output"),
templateDefined = $(".target-output").data("template-chosen"),
template = $("#mustacheTempalte_"+templateDefined).html();

var shows = { "shows" : [ 

{
	"name" : "Twin Room with Private Bathroom",
	"genius" : true,
	"high_demand": true,
	"high_demand": true,

	"pay_arrive": true,
	"choose_bed" : false,
	"beds": "4 bunk beds",
	"quantity" : "2",
	"air_cond" : true,
	"private_bathroom" : true,
	"wifi": true,
	"female_only" : "false",
	"private" : "private",
	"old_price" : "2919",
	"price" : "2627",
	"discount" : "25",
	"breakfast" : true,
},
{
	"name" : "Quadruple Room with Private Bathroom",
	"genius" : true,
	"pay_arrive": true,
	"beds": "4 bunk beds",
	"choose_bed" : true,
	"quantity" : "4",
	"air_cond" : true,
	"private_bathroom" : true,
	"private" : "Shared",
	"wifi": true,
	"old_price" : "4295",
	"price" : "3866",
	"discount" : "21",
	"breakfast" : true,
},
{
	"name" : "Double or Twin Room with Terrace",
	"genius" : true,
	"choose_bed" : true,
	"quantity" : "2",
	"private_bathroom" : true,
	"wifi": true,
	"old_price" : "4564",
	"price" : "4105",
	"discount" : "23",
	"breakfast" : true,
},
{
	"name" : "Room with 8 beds and Private Bathroom ",
	"genius" : true,
	"beds": "8 bunk beds",
	"quantity" : "8",
	"private" : "Shared",
	"private_bathroom" : true,
	"female_only" : "false",
	"choose_bed" : true,

	"wifi": true,
	"old_price" : "7165",
	"price" : "6448",
	"discount" : "23",
	"breakfast" : true,
},
{	"name" : "Bed in 8-Bed Mixed Dormitory Room",
"genius" : false,
"beds": "8 bunk beds",
"quantity" : "1",
"old_price" : "995",
"fem_only": false,
"private" : "Shared",
"price" : "896",
"private_bathroom" : true,
"wifi": false,
"female_only" : "false",
"discount" : "27",
"choose_bed" : true,

},

{
	"name" : "Bed in 8-Bed Female Dormitory Room",
	"genius" : false,
	"beds": "1 bunk bed",
	"quantity" : "1",
	"fem_only": true,
	"old_price" : "995",
	"price" : "896",
	"private_bathroom" : true,
	"wifi": true,
	"female_only" : "true",
	"discount" : "24",
	"choose_bed" : true,

},
{
	"name" : "Bed in 4-Bed Mixed Dormitory Room",
	"genius" : true,
	"high_demand": true,
	"cancelation": true,
	"choose_bed" : false,
	"quantity" : "4",
	"old_price" : "1988.39",
	"price" : "1657",
	"wifi": true,
	"private_bathroom" : false,
	"female_only" : "false",
	"private" : "Shared",
	"refundable" : true,
	"breakfast" : false
},
{
	"name" : "Bed in 6-Bed Mixed Dormitory Room",
	"genius" : true,
	"high_demand": true,
	"cancelation": true,
	"choose_bed" : true,
	"quantity" : "6",
	"old_price" : "1872",
	"price" : "1560",
	"wifi": true,
	
	"private_bathroom" : false,
	"female_only" : "false",
	"private" : "Shared",
	"refundable" : true,
	"breakfast" : false
},
{
	"name" : "Twin Room with Private Bathroom",
	"genius" : true,
	"high_demand": true,
	"pay_arrive": true,
	"choose_bed" : false,
	"quantity" : "2",
	"old_price" : "2203.2",
	"price" : "1836",
	"wifi": false,
	"private_bathroom" : true,
	"female_only" : "false",
	"private" : "private",
	"refundable" : false,
	"breakfast" : true,
},
{
	"name" : "Room with 6 beds and Private Bathroom",
	"genius" : true,
	"high_demand": false,
	"choose_bed" : true,
	"quantity" : "6",
	"old_price" : "2178",
	"price" : "1815",
	"private_bathroom" : true,
	"wifi": true,
	"female_only" : "false",
	"private" : "private",
	"refundable" : false,
	"breakfast" : true,
}
] };


var html = Mustache.render(template, shows);

$(targetContainer).html(html);